name: simple_music_player
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  simple_audio: ^1.4.3
  audiotags: ^1.1.0
  flutter_solidart: ^0.3.1
  file_picker: ^5.2.5
  tuple: ^2.0.1
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
